---
- name: Install DB
  hosts: all
  become: true
  tasks:
    - name: Add key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com
        state: present
    - name: Add repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: Install mongodb package
      apt:
        name: mongodb-org
        state: present
    - name: Enable mongod
      service: 
        name: mongod
        enabled: yes
